from student_info_db import engine, metadata, students
import sqlalchemy as db 

conn = engine.connect()

engine = db.create_engine('sqlite:///roommate_match.db')
metadata = db.MetaData()
conn = engine.connect()

students = db.Table('students', metadata, autoload_with=engine)


# Create dummy data (you can insert multiple students if you like
dummy_students = [
    {
        "name": "Josh Anderson",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Watching film, gaming, and hiking.",
        "fav_movies": "Avengers End Game, X-Men Days of Future Past",
        "music_genres": "R&B, Pop",
        "music_artists": "Steve Lacy",
        "instagram": "@nyc.josh",
        "email": "joshanderson@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Ben Brown",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Gaming, especially FPS games, and cooking new recipes.",
        "fav_movies": "John Wick, Spider-Man",
        "music_genres": "Hip-Hop, Rap",
        "music_artists": "Drake, Kendrick",
        "instagram": "@benb",
        "email": "benjib@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Salma Lopez",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Reading, especially latin american literature.",
        "fav_movies": "Mcfarland USA, Juno",
        "music_genres": "Pop, R&B",
        "music_artists": "The Marias, Malcolm Todd",
        "instagram": "@salma_l",
        "email": "salmalopez@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Eve Flores",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Cooking, baking, and playing video games.",
        "fav_movies": "La La Land, Star Wars Revenge of the Sith",
        "music_genres": "Chill, R&B, Rap",
        "music_artists": "Megan Thee Stallion, Cuco",
        "instagram": "@eve_flores",
        "email": "eveflores@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Denise Lillies",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Gyming, playing my guitar, and reading books.",
        "fav_movies": "The Notebook, 500 Days of Summer",
        "music_genres": "Chill, R&B, Rap",
        "music_artists": "Tyler The Creator, Mac DeMarco",
        "instagram": "@denise_l",
        "email": "deniselillies@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "David Diaz",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Basketball, working out, and watching documentaries.",
        "fav_movies": "The Batman, Parasite",
        "music_genres": "Rap, R&B, Rock",
        "music_artists": "Frank Ocean, Ian",
        "instagram": "@daviddiaz",
        "email": "daviddiaz@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Isabella Johnson",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Reading non-fiction, debates, and crafting.",
        "fav_movies": "Legally Blonde, Scott Pilgrim vs. The World",
        "music_genres": "Lo-fi, Chill",
        "music_artists": "Tame Impala, Joji",
        "instagram": "@isabell_j",
        "email": "isabellajohnson@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Jalen Cortes",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Working out, streaming games, and playing soccer.",
        "fav_movies": "Avengers: Endgame, Fast & Furious",
        "music_genres": "R&B, Rap",
        "music_artists": "21 Savage, Travis Scott",
        "instagram": "@jasonj",
        "email": "jason@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Cristian Castellanos",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Swimming, hiking, and playing video games.",
        "fav_movies": "The Batman, Ponyo, ",
        "music_genres": "R&B, Chill, Rap, Soul",
        "music_artists": "Malcolm Todd, The Marias, Tyler the Creator",
        "instagram": "@cristiann",
        "email": "ccastellanos@vassar.edu",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },  
    {
        "name": "Lucas Kim",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Skateboarding, anime, and coding.",
        "fav_movies": "Spirited Away, The Matrix",
        "music_genres": "Lo-fi, Rock",
        "music_artists": "Radiohead, Joji",
        "instagram": "@lucask",
        "email": "lucas.kim@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Aaliyah Jackson",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Dancing, podcasting, and yoga.",
        "fav_movies": "Step Up, Hidden Figures",
        "music_genres": "R&B, Pop",
        "music_artists": "SZA, Beyoncé",
        "instagram": "@aaliyahmoves",
        "email": "a.jackson@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Liam White",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Gaming, music production, and hiking.",
        "fav_movies": "Inception, Tenet",
        "music_genres": "EDM, Rap",
        "music_artists": "Kanye West, Flume",
        "instagram": "@liamw",
        "email": "liam.white@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Zara Nunez",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Fashion design, singing, and journaling.",
        "fav_movies": "Clueless, The Great Gatsby",
        "music_genres": "Pop, Soul",
        "music_artists": "Ariana Grande, Alicia Keys",
        "instagram": "@zaranunez",
        "email": "zaranunez@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Jake Thompson",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Running, cooking, and podcasts.",
        "fav_movies": "Creed, Moneyball",
        "music_genres": "Hip-Hop, Rock",
        "music_artists": "J. Cole, Red Hot Chili Peppers",
        "instagram": "@jaket",
        "email": "jakethompson@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Natalie Brooks",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Cycling, Netflix, and scrapbooking.",
        "fav_movies": "To All the Boys, The Kissing Booth",
        "music_genres": "Pop, Chill",
        "music_artists": "Olivia Rodrigo, Billie Eilish",
        "instagram": "@natbrooks",
        "email": "natalieb@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Omar Reyes",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Basketball, sneakers, and graphic design.",
        "fav_movies": "Black Panther, Space Jam",
        "music_genres": "Hip-Hop, Trap",
        "music_artists": "Lil Baby, JID",
        "instagram": "@omarrey",
        "email": "omar.reyes@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Grace Lin",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Photography, drawing, and piano.",
        "fav_movies": "Coco, Inside Out",
        "music_genres": "Classical, Chill",
        "music_artists": "Chopin, Yiruma",
        "instagram": "@gracecaptures",
        "email": "gracelin@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Tyrese Hall",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Gym, comedy shows, and crypto.",
        "fav_movies": "Rush Hour, The Hangover",
        "music_genres": "Rap, EDM",
        "music_artists": "Future, Travis Scott",
        "instagram": "@tyreseh",
        "email": "tyresehall@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Sofia Rivera",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Dancing, TikTok, and photography.",
        "fav_movies": "Encanto, Moana",
        "music_genres": "Reggaeton, Pop",
        "music_artists": "Bad Bunny, Rosalia",
        "instagram": "@sofiariv",
        "email": "sofia.rivera@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Jayden Carter",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Drumming, playing soccer, and watching anime.",
        "fav_movies": "Naruto: The Last, Endgame",
        "music_genres": "Rock, J-Pop",
        "music_artists": "UVERworld, Linkin Park",
        "instagram": "@jaycarter",
        "email": "jayden.c@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Ella Barnes",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Bullet journaling, yoga, and latte art.",
        "fav_movies": "Breakfast at Tiffany’s, A Silent Voice",
        "music_genres": "Indie Pop, Classical",
        "music_artists": "Clairo, Ryuichi Sakamoto",
        "instagram": "@ellajournals",
        "email": "ella.b@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Niko Tanaka",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Origami, building model kits, and speedcubing.",
        "fav_movies": "Akira, Ghost in the Shell",
        "music_genres": "Synthwave, Ambient",
        "music_artists": "Kavinsky, Oneohtrix Point Never",
        "instagram": "@niko_crafts",
        "email": "niko.t@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Miles Hawkins",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Birdwatching, astronomy, and hiking alone.",
        "fav_movies": "The Martian, Into the Wild",
        "music_genres": "Folk, Instrumental",
        "music_artists": "Fleet Foxes, Explosions in the Sky",
        "instagram": "@astro.miles",
        "email": "mileshawkins@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Ananya Deshmukh",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Classical Indian dance, poetry writing, and volunteering.",
        "fav_movies": "The Lunchbox, The Namesake",
        "music_genres": "Indian Classical, Indie",
        "music_artists": "Prateek Kuhad, AR Rahman",
        "instagram": "@ananya.poetry",
        "email": "ananya.deshmukh@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Jordan Vega",
        "age": 19,
        "pronouns": "they/he",
        "hobbies": "Zines, spoken word poetry, and roller skating.",
        "fav_movies": "Moonlight, Paris Is Burning",
        "music_genres": "Queer pop, Lo-fi",
        "music_artists": "Arca, Girl in Red",
        "instagram": "@vega.jordan",
        "email": "jordan.vega@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
        {
        "name": "Alejandro Ruiz",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Parkour, DJing, and digital art.",
        "fav_movies": "Baby Driver, Blade Runner 2049",
        "music_genres": "Trap, House",
        "music_artists": "Kaytranada, Travis Scott",
        "instagram": "@ale.ruiz",
        "email": "aruiz@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Juniper Leigh",
        "age": 18,
        "pronouns": "she/they",
        "hobbies": "Mushroom foraging, tarot, and sustainable fashion.",
        "fav_movies": "Coraline, Lady Bird",
        "music_genres": "Dream pop, Indie rock",
        "music_artists": "Beach House, Mitski",
        "instagram": "@junie.leigh",
        "email": "juniper.leigh@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Diego Martinez",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Tattoo sketching, boxing, and punk concerts.",
        "fav_movies": "Fight Club, Trainspotting",
        "music_genres": "Punk, Metal",
        "music_artists": "System of a Down, Bad Brains",
        "instagram": "@diegosketches",
        "email": "diego.martinez@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Fatima El-Sayed",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Calligraphy, coding, and writing sci-fi stories.",
        "fav_movies": "Arrival, Hidden Figures",
        "music_genres": "Classical, Electronic",
        "music_artists": "Ludovico Einaudi, ODESZA",
        "instagram": "@fatimawrites",
        "email": "fatima.es@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Amara Singh",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Classical singing, debate club, and learning languages.",
        "fav_movies": "Slumdog Millionaire, The Farewell",
        "music_genres": "Indian Classical, Jazz",
        "music_artists": "Ella Fitzgerald, Shreya Ghoshal",
        "instagram": "@amara_voice",
        "email": "amara.singh@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Theo Nguyen",
        "age": 18,
        "pronouns": "he/they",
        "hobbies": "Film photography, skating, and indie game development.",
        "fav_movies": "Everything Everywhere All At Once, Moonrise Kingdom",
        "music_genres": "Indie Rock, Lo-fi",
        "music_artists": "Japanese Breakfast, Steve Lacy",
        "instagram": "@nguyentheo",
        "email": "theo.n@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Bianca Rhodes",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Horseback riding, watercolor painting, and journaling.",
        "fav_movies": "Pride and Prejudice, Little Women",
        "music_genres": "Classical, Folk",
        "music_artists": "Lana Del Rey, Sufjan Stevens",
        "instagram": "@biancarhodes",
        "email": "bianca.rhodes@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Jorge Santiago",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Spoken word poetry, graffiti, and volunteering at shelters.",
        "fav_movies": "City of God, Roma",
        "music_genres": "Rap, Soul, Latin",
        "music_artists": "J. Cole, Residente, Lauryn Hill",
        "instagram": "@santiago.jorge",
        "email": "jorge.s@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Luz Rivera",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Sculpting, astrology, and crystal collecting.",
        "fav_movies": "Paprika, Eternal Sunshine of the Spotless Mind",
        "music_genres": "Experimental, Ambient",
        "music_artists": "Grimes, FKA Twigs",
        "instagram": "@luzrivera",
        "email": "luz.rivera@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Marcus Lee",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Weightlifting, fantasy novels, and chess.",
        "fav_movies": "The Witcher, The Lord of the Rings",
        "music_genres": "Trap, Orchestral",
        "music_artists": "Metro Boomin, Hans Zimmer",
        "instagram": "@marcuslift",
        "email": "marcus.lee@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Selene Park",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Crocheting, nature walks, and baking desserts.",
        "fav_movies": "Amélie, Ponyo",
        "music_genres": "K-Indie, Acoustic",
        "music_artists": "IU, Keshi",
        "instagram": "@selenestitches",
        "email": "selene.park@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Emilio Torres",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Coding, Dungeons & Dragons, and watching horror films.",
        "fav_movies": "The Thing, Ex Machina",
        "music_genres": "Electronic, Rock",
        "music_artists": "Deftones, Aphex Twin",
        "instagram": "@emiliotorres",
        "email": "emilio.t@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Renee Dupont",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Reading French literature, fencing, and piano.",
        "fav_movies": "Blue Is the Warmest Color, Amour",
        "music_genres": "French Pop, Classical",
        "music_artists": "Christine and the Queens, Debussy",
        "instagram": "@reneelivre",
        "email": "renee.dupont@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Dante Brooks",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Stand-up comedy, thrift shopping, and hosting game nights.",
        "fav_movies": "Superbad, Get Out",
        "music_genres": "Hip-Hop, Funk",
        "music_artists": "Anderson .Paak, Tyler The Creator",
        "instagram": "@dantefunny",
        "email": "dante.b@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Ines Moreau",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Museum hopping, philosophy, and vegan cooking.",
        "fav_movies": "Portrait of a Lady on Fire, Midnight in Paris",
        "music_genres": "French Jazz, Ambient",
        "music_artists": "Édith Piaf, Nujabes",
        "instagram": "@inesm.art",
        "email": "ines.moreau@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Tariq Abdul",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Spoken word, sneaker culture, and tech reviews.",
        "fav_movies": "Do the Right Thing, The Social Network",
        "music_genres": "Hip-Hop, Jazz Rap",
        "music_artists": "Kendrick Lamar, A Tribe Called Quest",
        "instagram": "@tariqtalks",
        "email": "tariq.abdul@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Yuki Nakamura",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Origami, indie game modding, and glitch art.",
        "fav_movies": "Paprika, Spirited Away",
        "music_genres": "Chiptune, Lo-fi",
        "music_artists": "Snail’s House, Kero Kero Bonito",
        "instagram": "@yuki.codes",
        "email": "yuki.nakamura@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Harper Quinn",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Urban sketching, longboarding, and indie podcasts.",
        "fav_movies": "Frances Ha, Boyhood",
        "music_genres": "Indie Folk, Shoegaze",
        "music_artists": "Mazzy Star, Big Thief",
        "instagram": "@harpersketches",
        "email": "harper.quinn@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Mateo Alvarez",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Cycling, salsa dancing, and puzzle-solving.",
        "fav_movies": "Coco, The Secret Life of Walter Mitty",
        "music_genres": "Latin Pop, Funk",
        "music_artists": "Carlos Vives, Bruno Mars",
        "instagram": "@mateocycles",
        "email": "mateo.alvarez@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Zehra Hussain",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Henna design, baking, and community organizing.",
        "fav_movies": "Persepolis, Queen of Katwe",
        "music_genres": "World, Acoustic",
        "music_artists": "Ali Zafar, Maher Zain",
        "instagram": "@zehra.artistry",
        "email": "zehra.h@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Andrei Petrov",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Speed chess, computer building, and classical piano.",
        "fav_movies": "Whiplash, The Imitation Game",
        "music_genres": "Classical, Techno",
        "music_artists": "Rachmaninoff, Deadmau5",
        "instagram": "@petrovandrei",
        "email": "andrei.petrov@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Mei Chen",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Calligraphy, tea tasting, and piano improv.",
        "fav_movies": "My Neighbor Totoro, The Farewell",
        "music_genres": "Chillhop, Classical",
        "music_artists": "Lofty, Yiruma",
        "instagram": "@meichn",
        "email": "mei.chen@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Dylan Hart",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Rock climbing, digital painting, and fantasy writing.",
        "fav_movies": "Pan's Labyrinth, Dune",
        "music_genres": "Alt Rock, Soundtrack",
        "music_artists": "Muse, Howard Shore",
        "instagram": "@dylanhartdraws",
        "email": "dylan.hart@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Sana Ahmed",
        "age": 19,
        "pronouns": "she/her",
        "hobbies": "Spiritual journaling, sewing, and vlogging.",
        "fav_movies": "A Silent Voice, The Breadwinner",
        "music_genres": "Indie Pop, Sufi",
        "music_artists": "Aurora, Abida Parveen",
        "instagram": "@sana.sews",
        "email": "sana.ahmed@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Nadia Belkacem",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Spoken poetry, ceramics, and journaling in Arabic and French.",
        "fav_movies": "Wadjda, Mustang",
        "music_genres": "North African folk, Jazz",
        "music_artists": "Souad Massi, Norah Jones",
        "instagram": "@nadia.words",
        "email": "nadia.belkacem@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Dev Patel",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Debating, listening to political podcasts, and coding bots.",
        "fav_movies": "12 Angry Men, Arrival",
        "music_genres": "Classical, Alternative Rock",
        "music_artists": "Radiohead, Hans Zimmer",
        "instagram": "@devcodes",
        "email": "dev.patel@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "River Blake",
        "age": 18,
        "pronouns": "they/them",
        "hobbies": "Spoken word, DIY zines, and rollerblading.",
        "fav_movies": "Perks of Being a Wallflower, Skate Kitchen",
        "music_genres": "Grunge, Indie Pop",
        "music_artists": "Girl in Red, Nirvana",
        "instagram": "@riverwrites",
        "email": "river.blake@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Fernando Jiménez",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Salsa dancing, cooking, and mechanical repairs.",
        "fav_movies": "Chef, Y Tu Mamá También",
        "music_genres": "Salsa, Reggaeton",
        "music_artists": "Marc Anthony, Bad Bunny",
        "instagram": "@fernandojmoves",
        "email": "fernando.j@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Sienna Walsh",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Hiking, geocaching, and writing eco-fiction.",
        "fav_movies": "The Secret Garden, Into the Wild",
        "music_genres": "Folk, Indie Acoustic",
        "music_artists": "Angus & Julia Stone, Iron & Wine",
        "instagram": "@siennawanders",
        "email": "sienna.walsh@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Elias Novak",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "3D modeling, Rubik’s cube speed solving, and sci-fi fanfiction.",
        "fav_movies": "Blade Runner, The Matrix",
        "music_genres": "Electronic, Synthwave",
        "music_artists": "Kavinsky, Daft Punk",
        "instagram": "@novak3d",
        "email": "elias.novak@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Minji Seo",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Calligraphy, K-drama reviews, and language exchange.",
        "fav_movies": "Parasite, My Sassy Girl",
        "music_genres": "K-Pop, R&B",
        "music_artists": "IU, Zion.T",
        "instagram": "@minji.cursive",
        "email": "minji.seo@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Ethan Price",
        "age": 18,
        "pronouns": "he/him",
        "hobbies": "Wrestling, crypto investing, and learning Excel shortcuts.",
        "fav_movies": "The Big Short, The Wolf of Wall Street",
        "music_genres": "Trap, EDM",
        "music_artists": "21 Savage, Marshmello",
        "instagram": "@ethan.finance",
        "email": "ethan.price@example.com",
        "cleanliness": "messy",
        "sleep_schedule": "late",
        "wakeup_time": "late",
        "contacted": False
    },
    {
        "name": "Lucía Delgado",
        "age": 18,
        "pronouns": "she/her",
        "hobbies": "Acrylic painting, thrift flipping, and fashion vlogging.",
        "fav_movies": "Amélie, Legally Blonde",
        "music_genres": "Pop, R&B",
        "music_artists": "Rosalía, Kali Uchis",
        "instagram": "@lu.delgado",
        "email": "lucia.delgado@example.com",
        "cleanliness": "neutral",
        "sleep_schedule": "late",
        "wakeup_time": "early",
        "contacted": False
    },
    {
        "name": "Tomas Eriksson",
        "age": 19,
        "pronouns": "he/him",
        "hobbies": "Cross-country skiing, photography, and environmental science.",
        "fav_movies": "The Revenant, March of the Penguins",
        "music_genres": "Classical, Nordic folk",
        "music_artists": "Sigur Rós, Ludovico Einaudi",
        "instagram": "@tomas.scansnow",
        "email": "tomas.eriksson@example.com",
        "cleanliness": "clean",
        "sleep_schedule": "early",
        "wakeup_time": "early",
        "contacted": False
    }
]

for student in dummy_students:
    insert_query = students.insert().values(student)
    try:
        conn.execute(insert_query)
    except db.exc.IntegrityError:
        pass

# Print all rows in the students table
select_query = db.select(students)
results = conn.execute(select_query).fetchall()
